# المنفذ الرئيسي للخدمة
listener 10000 0.0.0.0

# تحديد بروتوكول WebSockets
protocol websockets

# السماح بالاتصالات المجهولة (بدون اسم مستخدم وكلمة سر)
allow_anonymous true

# إيقاف التخزين الدائم للبيانات
persistence false

# توجيه السجلات للـ Console
log_dest stdout
connection_messages true
log_timestamp true
